### PR TITLE
Update joeybaker/remapify#26 to remapify@1.4.4

### PR DESCRIPTION
**Pull request by roncli**
The following issues from the original pull request at joeybaker/remapify#26 are addressed:
- Update remapify from 1.3.0 to 1.4.4
- Remove `.on('error', ...)` handler that is no longer compatible with the version of glob used in remapify 1.4.4

### CODE REVIEW

**Comment by jmm** [comment]
Hey @roncli, thanks for this. The sync globbing may not be neccessary, I have a possible lead on a solution. See my recent comment on joeybaker/remapify#26. But in case the sync globbing sticks around, what are the actual new commits here -- is it just  56aeb4f..584e9a0? Could your commits be rebased onto a more recent commit like c9b98f6?

**Comment by roncli** [comment]
Sounds good, I'll look into that.

This not based on c9b98f6, but rather on the next commit, b436835...   which is also the commit at which joeybaker/remapify#26 was originally posted.  While it looks like a lot, this PR just merges from joeybaker/remapify up to version 1.4.4, and then removes the `.on()` call that got removed from glob when remapify upgraded its glob dependency in 0abfc6d.

**Comment by jmm** [comment]
@roncli b43683514bff001aeb15cd0d1fa1cbe5c1ff08d2 is stale now because @joeybaker incorporated those changes separately. It would be better to avoid the merge commits in your pull request and keep the history simpler. If it turns out that the sync globbing is going to be used, I'll rebase my changes onto master and then you can rebase your change onto that and it'll keep the history nice and simple.

**Comment by roncli** [comment]
Oh, that would explain why test.js was showing up with merge conflicts... I see it now, in e4a8df9.  Fair enough. :)

I'm going to close this PR, and I'll wait to see what @joeybaker decides to do based on joeybaker/remapify#26 before I commit any more PR's.  Thanks for digging into this!

**Comment by jmm** [comment]
Thanks @roncli

**Pull request closed without merging**
